---
- name: java for centos
  include_tasks:
    java-centos.yml
  when:
    - ansible_facts.os_family == "RedHat"

- name: java for debian
  include_tasks:
    java-debian.yml
  when:
    - ansible_facts.os_family == 'Debian'
