---
- name: network restart
  systemd:
    name: "{{ os_network_service_name }}"
    state: restarted
  when: not ansible_check_mode

- name: bird restart
  systemd:
    name: bird
    state: restarted
    daemon-reload: true
  when: not ansible_check_mode

- name: firewalld restart
  systemd:
    name: firewalld
    state: restarted
