---
- name: daemons reloaded
  systemd:
    daemon_reload: true

- name: get package facts
  package_facts:
    manager: auto

- name: restart rsyslog
  service:
    name: rsyslog
    state: restarted

- name: reload sshd
  service:
    name: sshd
    state: reloaded
